#!/usr/bin/env python3
"""
Search SF5 UI docs manifest generated by build_ui_doc_atlas.py.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple


def score_record(record: Dict, terms: List[str]) -> int:
    haystacks = [
        record.get("path", "").lower(),
        record.get("title", "").lower(),
        record.get("description", "").lower(),
        " ".join(record.get("h2", [])).lower(),
    ]
    score = 0
    for term in terms:
        t = term.lower()
        if t in haystacks[0]:
            score += 5
        if t in haystacks[1]:
            score += 4
        if t in haystacks[2]:
            score += 3
        if t in haystacks[3]:
            score += 2
    return score


def main() -> int:
    parser = argparse.ArgumentParser(description="Search SF5 UI docs manifest.")
    parser.add_argument("--manifest", required=True, help="Path to ui-doc-manifest.json")
    parser.add_argument("query", nargs="+", help="Search terms")
    parser.add_argument("--limit", type=int, default=25, help="Max results")
    parser.add_argument("--top", default="", help="Filter by top section (utilities/start/...)")
    parser.add_argument(
        "--utility-group",
        default="",
        help="Filter by utility group (layout/grid/...)",
    )
    args = parser.parse_args()

    manifest_path = Path(args.manifest).expanduser().resolve()
    records: List[Dict] = json.loads(manifest_path.read_text(encoding="utf-8"))

    filtered: List[Tuple[int, Dict]] = []
    for rec in records:
        if args.top and rec.get("top") != args.top:
            continue
        if args.utility_group and rec.get("utility_group") != args.utility_group:
            continue
        s = score_record(rec, args.query)
        if s > 0:
            filtered.append((s, rec))

    filtered.sort(key=lambda item: (-item[0], item[1].get("path", "")))
    for score, rec in filtered[: args.limit]:
        print(
            f"[{score:02d}] {rec.get('path')} :: {rec.get('title')} "
            f"(top={rec.get('top')}, utility={rec.get('utility_group') or '-'})"
        )

    if not filtered:
        print("No matches.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
